const MIN_ID = 1;
const MAX_PHOTO_ID = 25;
const MAX_AVATAR_ID = 6;

const LIKES_MIN = 15;
const LIKES_MAX = 200;

const PHOTOS_TO_GENERATE = 25;
const COMMENT_MAX_LENGTH = 140;

const HASHTAG_PATTERN = /^#[a-zA-Z0-9]{1,19}$/;
const HASHTAGS_LIMIT = 5;

export {MIN_ID, MAX_PHOTO_ID,
  MAX_AVATAR_ID, LIKES_MIN, LIKES_MAX,
  PHOTOS_TO_GENERATE, COMMENT_MAX_LENGTH,
  HASHTAG_PATTERN, HASHTAGS_LIMIT};
